#!/bin/bash
TARGET_FILE="../server/src/persistence/schema/__init__.py"

echo "# DO NOT EDIT - autogenerated file. See database-gen project for details" > $TARGET_FILE
flask-sqlacodegen --flask sqlite:///../server/instance/dev.db >> $TARGET_FILE
