class EnvironmentConstantsKeys:
    GOOGLE_LOGIN_CLIENT_ID = 'GOOGLE_LOGIN_CLIENT_ID'
    PROJECT_MANAGER_EMAIL = 'PROJECT_MANAGER_EMAIL'
    JWT_SECRET_KEY = 'JWT_SECRET_KEY'
    APP_ENV = 'APP_ENV'
