"""Partially autogenerated - edit only inside manual sections"""
from . import db
'>>> manual imports section:'
'^^^ manual imports section'

class Business(db.Model):
    __tablename__ = 'business'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(256), nullable=False, unique=True)
    facebook_link = db.Column(db.String(2048))
    created_by = db.Column(db.ForeignKey('user.id'), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False)
    user = db.relationship('User', primaryjoin='Business.created_by == User.id', backref='businesses')
    '>>> manual class code section:'
    '^^^ manual class code section'