"""Partially autogenerated - edit only inside manual sections"""
from . import db
'>>> manual imports section:'
'^^^ manual imports section'

class Role(db.Model):
    __tablename__ = 'role'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(256), nullable=False, unique=True)
    '>>> manual class code section:'
    '^^^ manual class code section'