"""Partially autogenerated - edit only inside manual sections"""
from . import db
'>>> manual imports section:'
'^^^ manual imports section'

class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(256), nullable=False, unique=True)
    name = db.Column(db.String(256))
    avatar_url = db.Column(db.String(2048))
    '>>> manual class code section:'
    '^^^ manual class code section'