"""Partially autogenerated - edit only inside manual sections"""
from . import db
'>>> manual imports section:'
from typing import List
from .role import Role
'^^^ manual imports section'

class User(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(256), nullable=False, unique=True)
    name = db.Column(db.String(256))
    avatar_url = db.Column(db.String(2048))
    '>>> manual class code section:'

    @property
    def roles(self) -> List[Role]:
        return [user_role.role for user_role in self.user_roles]
    '^^^ manual class code section'